# For most projects, this workflow file will not need changing; you simply need
# to commit it to your repository.
#
# You may wish to alter this file to override the set of languages analyzed,
# or to provide custom queries or build logic.
#
# ******** NOTE ********
# We have attempted to detect the languages in your repository. Please check
# the `language` matrix defined below to confirm you have the correct set of
# supported CodeQL languages.
#
name: "GitHubDbCheckinAction"

on:
  push:
     branches:
     - "main"
  pull_request:
    types: [opened, reopened, edited]
  schedule:
    - cron: '24 17 * * 2'

jobs:
  analyze:
    name: DB Standard Checkin Policy
    runs-on: self-hosted
    permissions:
      actions: read
      contents: read
      security-events: write


    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: GitHubDbCheckinPolicy
      run: |
          C:\GitHubRepos\POH-Core\Source\POHCheckinPolicies\DatabaseStandards\bin\Debug\netcoreapp3.1\DatabaseStandards.exe ${{ github.event.number }} ${{ github.repository }} ${{ secrets.TESTTOKEN }}

    
